### PR TITLE
Implement importing events from the calendar

### PR DESCRIPTION
**Pull request by tirtow**
This PR adds a table view that populates with events from the calendar that the user can select to populate the fields when creating an event.

Things to consider:
- Set the max time forward for events to pull from the calendar to one month

Issues:
- Location on the imported event always seems to be empty/`nil`. Don't know if I'm doing something wrong.

### CODE REVIEW

**Comment by bzsinger** [comment]
Unless I'm missing something, it makes sense that location is usually empty -- most events in iCal don't have an associated location...

**Review by bzsinger — APPROVED** [review]
Looks great! 🇺🇸

**Comment by bzsinger** [comment]
Can you post a screen capture video? Otherwise, LGTM!

**Comment by tirtow** [comment]
ezgif com-video-to-gif

**Pull request merged**
