### PR TITLE
Finished Details Page Alpha Release

### PR DESCRIPTION
**Pull request by varunadiga**
added new view for contact information which we can make look prettier in the future. also got map zooming working
Simulator Screen Shot - iPhone Xʀ - 2019-03-27 at 17 11 59

Simulator Screen Shot - iPhone Xʀ - 2019-03-27 at 17 11 54

### CODE REVIEW

**Comment by varunadiga** [comment]
Simulator Screen Shot - iPhone Xʀ - 2019-03-27 at 19 56 00

**Comment by varunadiga** [comment]
Simulator Screen Shot - iPhone Xʀ - 2019-03-27 at 20 37 51

**Comment by varunadiga** [comment]
Simulator Screen Shot - iPhone Xʀ - 2019-03-27 at 21 53 43

**Review by bzsinger — APPROVED** [review]
🇺🇸

**Pull request merged**
