### PR TITLE
Loading indicators

### PR DESCRIPTION
**Pull request by tirtow**
**Important:** Please listen to [this](https://www.youtube.com/watch?v=PGNiXGX2nLU) while review this PR

**Also Important:** Approve and merge PR #54 before this PR

Adds a loading indicator to the officials table view using [NVActivityIndicatorView](https://github.com/ninjaprox/NVActivityIndicatorView):

loaders

### CODE REVIEW

**Comment by bzsinger** [comment]
I'm worried about bloating the repo the Pods/xcworkspace to the repo – can you add [these lines](https://github.com/github/gitignore/blob/master/Swift.gitignore#L43) to the gitignore and re-push (and add an "Install" section to the README that includes ```pod install```)?

**Review by bzsinger — CHANGES_REQUESTED** [review]
^

**Comment by tirtow** [comment]
@bzsinger I left the pods directory in based on [this](https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control) which was linked in our `.gitignore`.

**Review by bzsinger — APPROVED** [review]
Agreed to add Pod to repo based on offline conversation, 🦅

**Pull request merged**
